### ISSUE TITLE
案件画面（検査待ち、検査結果）での×ボタン非表示

### ISSUE THREAD

**Issue by JunichiroHonda** [recruit-tech/casval#12]
案件画面の案件登録したIP(HOST)の右上の×の制御について、
検査予約までは×ボタンはあってほしいが、検査待ちと検査結果では×ボタンは非表示にしてほしい。

**Comment by JunichiroHonda** [comment]
画面表示に関する要望のため、優先度：中でお願いします。

**Comment by nishimunea** [comment]
対応しないことが決まったためクローズします。
