### ISSUE TITLE
スキャン結果のSlackによる監視機能を追加

### ISSUE THREAD

**Issue by nishimunea** [recruit-tech/casval#2]
スキャン対象、スキャン結果（成否）、新規検出された脆弱性などをSlackで通知する。新規検出された脆弱性は、Slack上のリンクからCASVAL ORIGINの登録フォームを開き、「修正要否」や「コメント」をスムーズに登録できるようにする。

**Comment by JunichiroHonda** [comment]
追加のご相談です。
スキャン結果は完了次第、都度Slackで通知して頂きたいのですが、
それに加えて、例えば１日１回定点にてリスト形式でも通知して頂けないでしょうか。

**Comment by JunichiroHonda** [comment]
スキャン結果のみではなく、中断や失敗時の通知も欲しいです。Slack通知のバリエーションをリストで共有お願いいたします。

**Comment by takayukikaji** [comment]
https://drive.google.com/a/r-csirt.com/file/d/10itXcHi4KGt7Y7A0ENWnDDCwMUrqC4bC/view?usp=sharing

Slackの通知バリエーションの整理資料を共有致します。
不明点等は明日、対面でご説明させてください。
