### ISSUE TITLE
hostでのスキャン結果csvについて、host情報に加えIP情報も表示してほしい

### ISSUE THREAD

**Issue by takayukikaji** [recruit-tech/casval#5]
CSV項目について、host とは別に IP の項目が欲しい。
host を登録し検索した結果、CSVには host 情報の他に、関連付けられた IP も出力してほしい。
IP を登録し検索した場合、CSVの host 項目はブランクになる想定です。

**Comment by nishimunea** [comment]
レポートにIPアドレスが既に出力されているので、クローズします。
